affiliationHunter: QXNzb2NpYXRpb24gSHVudGVy
arcHunter: QXJjIGRlcyBLaW1lcmEgQW50cw==
classeAnimal: TWFtbWlmw6hyZQ==
couleurCheuveuxHunter: Tm9pcnM=
dietDino: Q2Fybml2b3Jl
epochDino: Q3LDqXRhY8Op
familleAnimal: Qm92aWTDqQ==
genreHunter: RmVtaW5pbg==
habitatAnimal: Rm9yZXQsIE1vbnRhZ25lcw==
heightDino: MC41
imageUrlHunter: aHR0cHM6Ly9wYnMudHdpbWcuY29tL21lZGlhL0VLSk1CUlZYc0FBcTQzWS5qcGc=
imgAnimal: aHR0cHM6Ly93d3cuem9vbG9naXN0ZS5jb20vL2ltYWdlcy9saXN0aW5nL2dhemVsbGUuanBn
imgDino: aHR0cHM6Ly9lbmNyeXB0ZWQtdGJuMC5nc3RhdGljLmNvbS9pbWFnZXM/cT10Ym46QU5kOUdjUjRoSFNtMHdFV20xVzU1V3RlYVc0dGlrMExhRk1RbUFKLXpKYXpBTFFlUUtDUlRETWxqTmVEaEZyLW13JmFtcDtz
locationDino: QXNpZQ==
locomotionDino: Qmlww6hkZQ==
nameAnimal: R2F6ZWxsZQ==
nameDino: VmVsb2NpcmFwdG9y
nameHunter: UGFtdSBTaGliZXJpYQ==
nenType: UmVuZm9yY2VtZW50
occupationHunter: SHVudGVy
poidsAnimal: NzU=
regimeAnimal: SGVyYml2b3Jl
tailleAnimal: MS4y
weightDino: MC4wMTU=
